/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _mainRouteRouteImport } from './routes/__main/route'
import { Route as _authRouteRouteImport } from './routes/__auth/route'
import { Route as _mainIndexRouteImport } from './routes/__main/index'
import { Route as _mainUserManagementRouteImport } from './routes/__main/user-management'
import { Route as _mainSubscriptionsRouteImport } from './routes/__main/subscriptions'
import { Route as _mainSettingsRouteImport } from './routes/__main/settings'
import { Route as _mainReportsRouteImport } from './routes/__main/reports'
import { Route as _mainPrayerManagementRouteImport } from './routes/__main/prayer-management'
import { Route as _mainPaymentsRouteImport } from './routes/__main/payments'
import { Route as _mainNotificationsRouteImport } from './routes/__main/notifications'
import { Route as _mainDailyContentRouteImport } from './routes/__main/daily-content'
import { Route as _mainCommunityRouteImport } from './routes/__main/community'
import { Route as _authVerificationRouteImport } from './routes/__auth/verification'
import { Route as _authSigninRouteImport } from './routes/__auth/signin'
import { Route as _authResetPasswordRouteImport } from './routes/__auth/reset-password'
import { Route as _authForgotPasswordRouteImport } from './routes/__auth/forgot-password'

const _mainRouteRoute = _mainRouteRouteImport.update({
  id: '/__main',
  getParentRoute: () => rootRouteImport,
} as any)
const _authRouteRoute = _authRouteRouteImport.update({
  id: '/__auth',
  getParentRoute: () => rootRouteImport,
} as any)
const _mainIndexRoute = _mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainUserManagementRoute = _mainUserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainSubscriptionsRoute = _mainSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainSettingsRoute = _mainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainReportsRoute = _mainReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainPrayerManagementRoute = _mainPrayerManagementRouteImport.update({
  id: '/prayer-management',
  path: '/prayer-management',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainPaymentsRoute = _mainPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainNotificationsRoute = _mainNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainDailyContentRoute = _mainDailyContentRouteImport.update({
  id: '/daily-content',
  path: '/daily-content',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainCommunityRoute = _mainCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _authVerificationRoute = _authVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authSigninRoute = _authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authResetPasswordRoute = _authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authForgotPasswordRoute = _authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => _authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof _mainIndexRoute
  '/forgot-password': typeof _authForgotPasswordRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/signin': typeof _authSigninRoute
  '/verification': typeof _authVerificationRoute
  '/community': typeof _mainCommunityRoute
  '/daily-content': typeof _mainDailyContentRoute
  '/notifications': typeof _mainNotificationsRoute
  '/payments': typeof _mainPaymentsRoute
  '/prayer-management': typeof _mainPrayerManagementRoute
  '/reports': typeof _mainReportsRoute
  '/settings': typeof _mainSettingsRoute
  '/subscriptions': typeof _mainSubscriptionsRoute
  '/user-management': typeof _mainUserManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof _mainIndexRoute
  '/forgot-password': typeof _authForgotPasswordRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/signin': typeof _authSigninRoute
  '/verification': typeof _authVerificationRoute
  '/community': typeof _mainCommunityRoute
  '/daily-content': typeof _mainDailyContentRoute
  '/notifications': typeof _mainNotificationsRoute
  '/payments': typeof _mainPaymentsRoute
  '/prayer-management': typeof _mainPrayerManagementRoute
  '/reports': typeof _mainReportsRoute
  '/settings': typeof _mainSettingsRoute
  '/subscriptions': typeof _mainSubscriptionsRoute
  '/user-management': typeof _mainUserManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__auth': typeof _authRouteRouteWithChildren
  '/__main': typeof _mainRouteRouteWithChildren
  '/__auth/forgot-password': typeof _authForgotPasswordRoute
  '/__auth/reset-password': typeof _authResetPasswordRoute
  '/__auth/signin': typeof _authSigninRoute
  '/__auth/verification': typeof _authVerificationRoute
  '/__main/community': typeof _mainCommunityRoute
  '/__main/daily-content': typeof _mainDailyContentRoute
  '/__main/notifications': typeof _mainNotificationsRoute
  '/__main/payments': typeof _mainPaymentsRoute
  '/__main/prayer-management': typeof _mainPrayerManagementRoute
  '/__main/reports': typeof _mainReportsRoute
  '/__main/settings': typeof _mainSettingsRoute
  '/__main/subscriptions': typeof _mainSubscriptionsRoute
  '/__main/user-management': typeof _mainUserManagementRoute
  '/__main/': typeof _mainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/verification'
    | '/community'
    | '/daily-content'
    | '/notifications'
    | '/payments'
    | '/prayer-management'
    | '/reports'
    | '/settings'
    | '/subscriptions'
    | '/user-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/verification'
    | '/community'
    | '/daily-content'
    | '/notifications'
    | '/payments'
    | '/prayer-management'
    | '/reports'
    | '/settings'
    | '/subscriptions'
    | '/user-management'
  id:
    | '__root__'
    | '/__auth'
    | '/__main'
    | '/__auth/forgot-password'
    | '/__auth/reset-password'
    | '/__auth/signin'
    | '/__auth/verification'
    | '/__main/community'
    | '/__main/daily-content'
    | '/__main/notifications'
    | '/__main/payments'
    | '/__main/prayer-management'
    | '/__main/reports'
    | '/__main/settings'
    | '/__main/subscriptions'
    | '/__main/user-management'
    | '/__main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authRouteRoute: typeof _authRouteRouteWithChildren
  _mainRouteRoute: typeof _mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__main': {
      id: '/__main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__main/': {
      id: '/__main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _mainIndexRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/user-management': {
      id: '/__main/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof _mainUserManagementRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/subscriptions': {
      id: '/__main/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof _mainSubscriptionsRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/settings': {
      id: '/__main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof _mainSettingsRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/reports': {
      id: '/__main/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof _mainReportsRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/prayer-management': {
      id: '/__main/prayer-management'
      path: '/prayer-management'
      fullPath: '/prayer-management'
      preLoaderRoute: typeof _mainPrayerManagementRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/payments': {
      id: '/__main/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof _mainPaymentsRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/notifications': {
      id: '/__main/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof _mainNotificationsRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/daily-content': {
      id: '/__main/daily-content'
      path: '/daily-content'
      fullPath: '/daily-content'
      preLoaderRoute: typeof _mainDailyContentRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/community': {
      id: '/__main/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof _mainCommunityRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__auth/verification': {
      id: '/__auth/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof _authVerificationRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/signin': {
      id: '/__auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof _authSigninRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/reset-password': {
      id: '/__auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof _authResetPasswordRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/forgot-password': {
      id: '/__auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof _authForgotPasswordRouteImport
      parentRoute: typeof _authRouteRoute
    }
  }
}

interface _authRouteRouteChildren {
  _authForgotPasswordRoute: typeof _authForgotPasswordRoute
  _authResetPasswordRoute: typeof _authResetPasswordRoute
  _authSigninRoute: typeof _authSigninRoute
  _authVerificationRoute: typeof _authVerificationRoute
}

const _authRouteRouteChildren: _authRouteRouteChildren = {
  _authForgotPasswordRoute: _authForgotPasswordRoute,
  _authResetPasswordRoute: _authResetPasswordRoute,
  _authSigninRoute: _authSigninRoute,
  _authVerificationRoute: _authVerificationRoute,
}

const _authRouteRouteWithChildren = _authRouteRoute._addFileChildren(
  _authRouteRouteChildren,
)

interface _mainRouteRouteChildren {
  _mainCommunityRoute: typeof _mainCommunityRoute
  _mainDailyContentRoute: typeof _mainDailyContentRoute
  _mainNotificationsRoute: typeof _mainNotificationsRoute
  _mainPaymentsRoute: typeof _mainPaymentsRoute
  _mainPrayerManagementRoute: typeof _mainPrayerManagementRoute
  _mainReportsRoute: typeof _mainReportsRoute
  _mainSettingsRoute: typeof _mainSettingsRoute
  _mainSubscriptionsRoute: typeof _mainSubscriptionsRoute
  _mainUserManagementRoute: typeof _mainUserManagementRoute
  _mainIndexRoute: typeof _mainIndexRoute
}

const _mainRouteRouteChildren: _mainRouteRouteChildren = {
  _mainCommunityRoute: _mainCommunityRoute,
  _mainDailyContentRoute: _mainDailyContentRoute,
  _mainNotificationsRoute: _mainNotificationsRoute,
  _mainPaymentsRoute: _mainPaymentsRoute,
  _mainPrayerManagementRoute: _mainPrayerManagementRoute,
  _mainReportsRoute: _mainReportsRoute,
  _mainSettingsRoute: _mainSettingsRoute,
  _mainSubscriptionsRoute: _mainSubscriptionsRoute,
  _mainUserManagementRoute: _mainUserManagementRoute,
  _mainIndexRoute: _mainIndexRoute,
}

const _mainRouteRouteWithChildren = _mainRouteRoute._addFileChildren(
  _mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _authRouteRoute: _authRouteRouteWithChildren,
  _mainRouteRoute: _mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
